### ISSUE TITLE
Error launching Ngobrol.AI: Template file 2023_SAFE.bin not found

### ISSUE THREAD

**Issue by oh64** [andri-jpg/ngobrol.ai#1]
~ $ python ngobrol.py
thread '<unnamed>' panicked at src/models.rs:9:1:
called `Result::unwrap()` on an `Err` value: FileDoesNotExist { path: "2023_SAFE.bin" }
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/ngobrol.py", line 70, in <module>
    generator = Chainer()
                ^^^^^^^^^
  File "/data/data/com.termux/files/home/ngobrol.py", line 37, in __init__
    self.model = Gpt2("2023_SAFE.bin", session_config=session_config)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pyo3_runtime.PanicException: called `Result::unwrap()` on an `Err` value: FileDoesNotExist { path: "2023_SAFE.bin" }

![Screenshot_2024-08-24-14-37-47-888_com termux-edit](https://github.com/user-attachments/assets/c457e337-7828-4cb1-ac14-6287d6d244ae)

~ $ RUST_BACKTRACE=full python ngobrol.py
thread '<unnamed>' panicked at src/models.rs:9:1:
called `Result::unwrap()` on an `Err` value: FileDoesNotExist { path: "2023_SAFE.bin" }
stack backtrace:
   0:       0x7608c34c00 - <unknown>
   1:       0x7608c50000 - <unknown>
   2:       0x7608c1f704 - <unknown>
   3:       0x7608c34a3c - <unknown>
   4:       0x7608c2a8d0 - <unknown>
   5:       0x7608c2a518 - <unknown>
   6:       0x7608c2ae4c - <unknown>
   7:       0x7608c35134 - <unknown>
   8:       0x7608c34e44 - <unknown>
   9:       0x7608c2aa94 - <unknown>
  10:       0x7608c4e814 - <unknown>
  11:       0x7608c4ebb0 - <unknown>
  12:       0x7608786888 - <unknown>
  13:       0x7608787328 - <unknown>
  14:       0x760877efa8 - <unknown>
  15:       0x7608786e34 - <unknown>
  16:       0x7694d0cfb4 - <unknown>
  17:       0x7694ca92c4 - <unknown>
  18:       0x7694d88940 - <unknown>
  19:       0x7694d83f44 - <unknown>
  20:       0x7694ca90c0 - <unknown>
  21:       0x7694ca9e84 - <unknown>
  22:       0x7694d1730c - <unknown>
  23:       0x7694d0d0f8 - <unknown>
  24:       0x7694ca92c4 - <unknown>
  25:       0x7694d88940 - <unknown>
  26:       0x7694d83df4 - <unknown>
  27:       0x7694dd7c1c - <unknown>
  28:       0x7694dd5f64 - <unknown>
  29:       0x7694dd5940 - <unknown>
  30:       0x7694df65cc - <unknown>
  31:       0x7694df5d28 - <unknown>
  32:       0x7694df5f84 - <unknown>
  33:       0x7694df602c - <unknown>
  34:       0x76945139a0 - <unknown>
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/ngobrol.py", line 70, in <module>
    generator = Chainer()
                ^^^^^^^^^
  File "/data/data/com.termux/files/home/ngobrol.py", line 37, in __init__
    self.model = Gpt2("2023_SAFE.bin", session_config=session_config)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pyo3_runtime.PanicException: called `Result::unwrap()` on an `Err` value: FileDoesNotExist { path: "2023_SAFE.bin" }

**Comment by andri-jpg** [comment]
I accidentally removed the original model. However, you can still use it by pasting the script below into Termux and running `ngobrol.py` again:

```bash
wget -O 2023_SAFE.meta https://huggingface.co/AndriLawrence/gpt2-chatkobi-ai/resolve/dc6a8f9bcb44448a398c1d0caee8d33d9d6d6f2a/ngobrol.meta
wget -O 2023_SAFE.bin https://huggingface.co/AndriLawrence/gpt2-chatkobi-ai/resolve/dc6a8f9bcb44448a398c1d0caee8d33d9d6d6f2a/ngobrol.bin
```

Please note that this model is in Indonesian language

**Comment by oh64** [comment]
It did that
And how to find an English/other version ?

~ $ python ngobrol.py                                   
Illegal instruction

**Comment by andri-jpg** [comment]
> It did that And how to find an English/other version ?
> 
> ~ $ python ngobrol.py Illegal instruction

Actually i'm not planning to make english version for this repo, anyway if you want to chat with llm in android and use english model, you can use this repo https://github.com/Mobile-Artificial-Intelligence/maid  which is provide more feature and advanced model.
